apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventree-data
  namespace: inventree
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path