apiVersion: v1
kind: Secret
metadata:
  name: inventree-admin-secret
  namespace: inventree
type: Opaque
data:
  INVENTREE_ADMIN_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=
  INVENTREE_ADMIN_PASSWORD: YWRtaW4=
  INVENTREE_ADMIN_USER: YWRtaW4=
  POSTGRES_USER: aW52ZW50cmVl
  POSTGRES_PASSWORD: aW52ZW50cmVl
  POSTGRES_DB: aW52ZW50cmVl
