apiVersion: v1
kind: Secret
metadata:
  name: inventree-admin-secret
  namespace: inventree
type: Opaque
data:
  INVENTREE_ADMIN_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=
  INVENTREE_ADMIN_PASSWORD: YWRtaW4=
  INVENTREE_ADMIN_USER: YWRtaW4=
  INVENTREE_DB_ENGINE: postgresql
  INVENTREE_DB_HOST: postgres.inventree.svc.cluster.local
  INVENTREE_DB_PORT: 5432
  INVENTREE_DB_NAME: aW52ZW50cmVl
  INVENTREE_DB_USER: aW52ZW50cmVl
  INVENTREE_DB_PASSWORD: aW52ZW50cmVl
