apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventree
  namespace: inventree
  labels:
    app.kubernetes.io/instance: inventree
    app.kubernetes.io/name: inventree
automountServiceAccountToken: true