apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-16gi
  labels:
    app: postgresql
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/postgres-data-16gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - convers-avia-k8s-node
