# values.yaml

# --- Настройка Ingress для доступа к UI ---
ingress:
  enabled: true
  hosts:
    - rp.store
    - rp.doc # Замените на ваш домен

# --- Ресурсы Parent-пода ---
parent:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

# --- Ресурсы Child-подов (DaemonSet) ---
child:
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

# --- Хранение данных ---
# Укажите ваш StorageClass, если он не 'default'
# database:
#   storageclass: 'your-single-zone-storage-class'
  volumesize: 10Gi
