apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-ngx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Источник 1: Helm-чарт от pascaliske
    - repoURL: https://pascaliske.github.io/helm-charts
      chart: paperless
      targetRevision: "7.0.0"
      helm:
        valueFiles:
          - $values/apps/paperless-ngx/values.yaml
    # Источник 2: Ваш Git-репозиторий
    - repoURL: https://github.com/SharkDeveloper/conversavia-avia-k8s-manifects.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: paperless-ngx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
