apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # Если ingress-nginx работает в HTTP и TLS не нужен — оставляем false.
    # Если нужен HTTPS с редиректом — поставьте "true" и добавьте tls-блок ниже.
spec:
  ingressClassName: nginx
  rules:
    - host: rp.doc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless-ngx       
                port:
                  number: 8000             

  # tls:
  #   - hosts:
  #       - rp.doc
  #     secretName: rp-doc-tls
