# secret.yaml (применить вручную, НЕ коммитить в Git)
apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx-secret
  namespace: paperless-ngx
type: Opaque
stringData:
  # Используйте ключи, ожидаемые чартом
  paperless-user: "admin"
  paperless-pass: "admin"
  paperless-mail: "admin@yourdomain.com"